###
# Dummy endpoint call to see 401 without Auth Bearer token
# GET profile
GET http://localhost:3000/api/profile


###
# Call endpoint to generate Authorization Bearer token
# POST auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "changeme"
}


###
# Call endpoint with generate above Authorization Bearer token to get ciurrent user's profile
# POST profile
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY0MjE2MjI2OSwiZXhwIjoxNjQyMTYyMzI5fQ.AT6TgPARiOTZGiks4SddG0HAG7vJh6-rpLbathcD7H8
