export interface ConfigurationInterface {
  YMRLK_MONGODB_CONNECTION_STRING: string;
  YMRLK_MONGODB_DATABASE: string;
  YMRLK_MONGODB_RETRY_ATTEMPTS: string;
  YMRLK_MONGODB_RETRY_DELAY: string;
  YMRLK_MONGODB_RETRY_DELAY_USER: string;
  YMRLK_MONGODB_RETRY_DELAY_PASSWORD: string;
  YMRLK_THROTTLE_TTL: string;
  YMRLK_THROTTLE_LIMIT: string;
  YMRLK_JWT_SECRET: string;
  YMRLK_JWT_EXPIRES_IN: string;
}

export const configuration: ConfigurationInterface = {
  YMRLK_MONGODB_CONNECTION_STRING:      'YMRLK_MONGODB_CONNECTION_STRING',
  YMRLK_MONGODB_DATABASE:               'YMRLK_MONGODB_DATABASE',
  YMRLK_MONGODB_RETRY_ATTEMPTS:         'YMRLK_MONGODB_RETRY_ATTEMPTS',
  YMRLK_MONGODB_RETRY_DELAY:            'YMRLK_MONGODB_RETRY_DELAY',
  YMRLK_MONGODB_RETRY_DELAY_USER:       'YMRLK_MONGODB_RETRY_DELAY_USER',
  YMRLK_MONGODB_RETRY_DELAY_PASSWORD:   'YMRLK_MONGODB_RETRY_DELAY_PASSWORD',
  YMRLK_THROTTLE_TTL:                   'YMRLK_THROTTLE_TTL',
  YMRLK_THROTTLE_LIMIT:                 'YMRLK_THROTTLE_LIMIT',
  YMRLK_JWT_SECRET:                     'YMRLK_JWT_SECRET',
  YMRLK_JWT_EXPIRES_IN:                 'YMRLK_JWT_EXPIRES_IN'
};
